name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - name: Install pulseaudio
      run: sudo apt-get update; sudo apt-get install -y pulseaudio
    - name: Test
      run: make test
    - name: Lint
      run: make lint
